name: Get current datetime from default Ubuntu command

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current datetime
      run: |
        CURRENTDATETIME=`date +"%A, %b %d, %Y %H:%M:%S"`
        echo Current Date and Time is: ${CURRENTDATETIME}
