name: CI Jobs
on:
    push: 
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
    print-date:
        runs-on: ubuntu-latest
        steps:
          - name: Print date to console
            run: echo Today is $(date)
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Build with Maven
          run: mvn verify
